---
title: Setting Up This Site
author: Abi Dawson
date: '2017-06-19'
slug: setting-up
categories: []
tags: []
Categories:
Description: 
Tags:
  - Hugo
  - GitHub
  - blogdown
menu: main
---

To kick things off, I want to share some details about how I created this site in case they're helpful for anyone else in the future. 

I landed on the GitHub/Hugo/blogdown workflow after some Google searching and went with it for a few reasons:  

* I already had a GitHub account and wanted to get more practice using git, and take advantage of the free hosting options there.
* Amber Thomas provides a [walkthrough](https://proquestionasker.github.io/blog/Making_Site/) of setting up a Hugo site using blogdown, and she made it look pretty simple. Her site is also an inspiring example.
* I like the idea of using an R package, blogdown, to do the heavy lifting of creating the site structure and generating post templates. There's bookdown documentation on it [here](https://bookdown.org/yihui/blogdown/) (co-written by Amber Thomas and Yihui Xie of knitr and bookdown).

## Getting Started

I first tried following Amber's instructions to set up the somewhat complicated Github Pages workflow, but got stuck on the setup.sh script step - on the last step in the script I kept getting an error reading `fatal: refusing to merge unrelated histories`. 

After struggling to diagnose the issue, I switched to another [tutorial](http://robertmyles.github.io/2017/02/01/how-to-make-a-github-pages-blog-with-rstudio-and-hugo/) by Robert Myles McDonnell that I found in the comments of Amber's post. This one had a slightly different workflow involving submodules instead of subtrees and worked better for me. 

The only thing that tripped me up here was that the instructions mention committing and pushing files from the public directory and viewing the published site before they mention running the `build_site()` command. I hadn't built the site yet, so when I committed there were no files to add or push and when I checked the live site URL there was nothing there. After I ran `build_site()`, everything worked fine.

## Themes and Code Chunk Syntax Highlighting

Once I was up and running, I needed to choose a [theme](https://themes.gohugo.io/). Aesthetic choices are always tough, and Hugo themes seem to have some differences in structure as well, so my choice would have functional implications, at least until I get a better handle on how to make modifications. Additionally, the blogdown documentation warns that "the more effort you make in a complicated theme, the more difficult it is to switch to other themes in the future, because you may have customized a lot of things that are not straightforward to port to another theme". This upped the intimidation factor a little (knowing that I might be stuck with my choice for a while). I picked [blackburn](https://themes.gohugo.io/blackburn/) because it is minimal, has a sidebar, and I liked the fonts. 

The only thing I didn't like about the appearance of my site after installing the theme was the code syntax highlighting, which had a black background and looked jarring within a blog post. After some googling I found [this GitHub issue](https://github.com/rstudio/blogdown/issues/10) which helped me understand the [Hugo documentation on syntax highlighting](https://gohugo.io/extras/highlighting/). I added these lines to my header.html file to use Highlight.js and was happy with the results.

``` html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.6.0/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.6.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

```